// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eVote360.Infrastructure.Persistence.Contexts;

#nullable disable

namespace eVote360.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VoteAppContext))]
    [Migration("20260215032954_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Alianza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAceptacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PartidoAId")
                        .HasColumnType("int");

                    b.Property<int>("PartidoBId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidoAId");

                    b.HasIndex("PartidoBId");

                    b.ToTable("Alianzas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Alianza_A_B_Distintos", "[PartidoAId] <> [PartidoBId]");
                        });
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.AlianzaSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSolicitudUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PartidoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("PartidoSolicitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidoDestinoId");

                    b.HasIndex("PartidoSolicitanteId");

                    b.ToTable("AlianzasSolicitudes", null, t =>
                        {
                            t.HasCheckConstraint("CK_AlianzaSolicitud_Solicitante_Destino", "[PartidoSolicitanteId] <> [PartidoDestinoId]");
                        });
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int?>("PuestoElectivoOrigenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.HasIndex("PuestoElectivoOrigenId");

                    b.ToTable("Candidatos", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Candidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int>("PuestoElectivoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("PuestoElectivoId");

                    b.HasIndex("PartidoId", "CandidatoId")
                        .IsUnique();

                    b.HasIndex("PartidoId", "PuestoElectivoId")
                        .IsUnique();

                    b.ToTable("Candidaturas", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Ciudadano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique();

                    b.ToTable("Ciudadanos", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.DirigentePartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DirigentesPartidos", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Eleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRealizacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Elecciones", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.EleccionCandidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidaturaId")
                        .HasColumnType("int");

                    b.Property<int>("EleccionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CandidaturaId");

                    b.HasIndex("EleccionId", "CandidaturaId")
                        .IsUnique();

                    b.ToTable("EleccionCandidaturas", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.EleccionPuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EleccionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PuestoElectivoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PuestoElectivoId");

                    b.HasIndex("EleccionId", "PuestoElectivoId")
                        .IsUnique();

                    b.ToTable("EleccionPuestos", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Siglas")
                        .IsUnique();

                    b.ToTable("Partidos", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PuestoElectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PuestosElectivos", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<int?>("CandidaturaId")
                        .HasColumnType("int");

                    b.Property<int>("CiudadanoId")
                        .HasColumnType("int");

                    b.Property<int>("EleccionId")
                        .HasColumnType("int");

                    b.Property<bool>("EsNinguno")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEmisionUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int>("PuestoElectivoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("CandidaturaId");

                    b.HasIndex("CiudadanoId");

                    b.HasIndex("EleccionId");

                    b.HasIndex("PartidoId");

                    b.HasIndex("PuestoElectivoId");

                    b.ToTable("Votos", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Alianza", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.Partido", "PartidoA")
                        .WithMany("AlianzasA")
                        .HasForeignKey("PartidoAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.Partido", "PartidoB")
                        .WithMany("AlianzasB")
                        .HasForeignKey("PartidoBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartidoA");

                    b.Navigation("PartidoB");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.AlianzaSolicitud", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.Partido", "PartidoDestino")
                        .WithMany("SolicitudesRecibidas")
                        .HasForeignKey("PartidoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.Partido", "PartidoSolicitante")
                        .WithMany("SolicitudesEnviadas")
                        .HasForeignKey("PartidoSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartidoDestino");

                    b.Navigation("PartidoSolicitante");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Candidato", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.Partido", "Partido")
                        .WithMany("Candidatos")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.PuestoElectivo", "PuestoElectivoOrigen")
                        .WithMany("CandidatosOrigen")
                        .HasForeignKey("PuestoElectivoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Partido");

                    b.Navigation("PuestoElectivoOrigen");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Candidatura", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.Candidato", "Candidato")
                        .WithMany("Candidaturas")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.Partido", "Partido")
                        .WithMany("Candidaturas")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.PuestoElectivo", "PuestoElectivo")
                        .WithMany("Candidaturas")
                        .HasForeignKey("PuestoElectivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Partido");

                    b.Navigation("PuestoElectivo");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.DirigentePartido", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.Partido", "Partido")
                        .WithMany("DirigentePartidos")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.Usuario", "Usuario")
                        .WithMany("DirigentePartidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.EleccionCandidatura", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.Candidatura", "Candidatura")
                        .WithMany("EleccionCandidaturas")
                        .HasForeignKey("CandidaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.Eleccion", "Eleccion")
                        .WithMany("EleccionCandidaturas")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidatura");

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.EleccionPuesto", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.Eleccion", "Eleccion")
                        .WithMany("EleccionPuestos")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.PuestoElectivo", "PuestoElectivo")
                        .WithMany("EleccionPuestos")
                        .HasForeignKey("PuestoElectivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleccion");

                    b.Navigation("PuestoElectivo");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Voto", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.Candidato", "Candidato")
                        .WithMany("Votos")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eVote360.Core.Domain.Entities.Candidatura", "Candidatura")
                        .WithMany("Votos")
                        .HasForeignKey("CandidaturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eVote360.Core.Domain.Entities.Ciudadano", "Ciudadano")
                        .WithMany("Votos")
                        .HasForeignKey("CiudadanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.Eleccion", "Eleccion")
                        .WithMany("Votos")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId");

                    b.HasOne("eVote360.Core.Domain.Entities.PuestoElectivo", "PuestoElectivo")
                        .WithMany("Votos")
                        .HasForeignKey("PuestoElectivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Candidatura");

                    b.Navigation("Ciudadano");

                    b.Navigation("Eleccion");

                    b.Navigation("Partido");

                    b.Navigation("PuestoElectivo");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Candidato", b =>
                {
                    b.Navigation("Candidaturas");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Candidatura", b =>
                {
                    b.Navigation("EleccionCandidaturas");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Ciudadano", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Eleccion", b =>
                {
                    b.Navigation("EleccionCandidaturas");

                    b.Navigation("EleccionPuestos");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Partido", b =>
                {
                    b.Navigation("AlianzasA");

                    b.Navigation("AlianzasB");

                    b.Navigation("Candidatos");

                    b.Navigation("Candidaturas");

                    b.Navigation("DirigentePartidos");

                    b.Navigation("SolicitudesEnviadas");

                    b.Navigation("SolicitudesRecibidas");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PuestoElectivo", b =>
                {
                    b.Navigation("CandidatosOrigen");

                    b.Navigation("Candidaturas");

                    b.Navigation("EleccionPuestos");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("DirigentePartidos");
                });
#pragma warning restore 612, 618
        }
    }
}
